### PR TITLE
LPS-68567 Fix regular expression

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares https://github.com/ctampoya/liferay-portal/pull/24 fixes the issue in which data provider links are lost after save the form again.
We also need the UI for autofill to get everything working as expected as we create data provider links when we save DDMStructure. Export feature just looks to those links.

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:stop

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43893. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/3c8a4d6~1...3c8a4d6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@leoadb, I've forwarded by this is extremely fragile :(

**Comment by leoadb** [comment]
@marcellustavares Do you mean it's fragile because we're using regex ?

**Comment by marcellustavares** [comment]
Two things came to my mind, we do not validate those expressions at `DDFormValidator` service (syntax and format) and we're not considering spaces between the tokens in the regex.

**Comment by leoadb** [comment]
Actually we're handling spaces (.*). Usually we have space after a comma, right ?

**Comment by marcellustavares** [comment]
can't the user type before `(` or `)` ?

**Comment by leoadb** [comment]
I tend to think that user wouldn't type this kind of expression. Wouldn't it be generated by user interaction ?

**Comment by marcellustavares** [comment]
actually it's available thru DDM API. For most cases I agree they would be using the UI.

**Pull request closed without merging**
