### PR TITLE
LPS-70790

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/2823 for more information

**Comment by yuhai** [comment]
Hi Marcellus,

Hope your are well.

The issue came from EE customer. Could you please review the PR when you have free time? 

Regards,
Hai

**Comment by yuhai** [comment]
Hi Marcellus,

Sorry to bother you. 

Since this ticket has been under review for several days and this is a EE customer fix, would it be possible for you to check this pull request with higher priority?

Regards,
Hai

**Comment by marcellustavares** [comment]
Sorry @yuhai, I was out of office last week. will take a look at this asap.

Thanks

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47338. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
