### PR TITLE
LPS-61361 Update preview view and edit click access

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
This is really beautiful @inacionery! :clap: :clap: :clap:

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/136. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/1273bde~1...1273bde) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
