### PR TITLE
FAKE GRADLE CACHE TO REMOVE

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
cc @mbowerman Thanks Michael! You did a wonderful work here. Sorry for all the delay. We are going to get it done!

**Comment by marcellustavares** [comment]
hey @mbowerman @brandizzi, we shouldn't be using fake cache here, just switch to project reference instead.

**Comment by marcellustavares** [comment]
@mbowerman, there're some poshi failures, are they related to this change?

Thanks for the help!

cc @vicnate5

**Comment by mbowerman** [comment]
@marcellustavares Looks like a lot of the poshi failures are related to calendar, so they're probably related to this change, but it might be that we need to change the tests to accommodate the new behavior of recurring calendar bookings.

**Comment by marcellustavares** [comment]
Thanks for the quick response @mbowerman, I'll talk to @vicnate5 about this.

Regards,

**Comment by vicnate5** [comment]
@marcellustavares @mbowerman This looks like a regression. Calendar is not accessible by the user and is missing from the staging configuration screen.

calendar

**Comment by marcellustavares** [comment]
@mbowerman, could you please take a look at this?

**Comment by mbowerman** [comment]
@marcellustavares Sure, I'll take a look at it.

**Comment by marcellustavares** [comment]
cool, thanks a lot 😄 !

**Comment by mbowerman** [comment]
The calendar module appears to not deploy correctly due to a compile error in the calendar-test submodule. It's likely a problem with the build.gradle file. I'll see if I can find a way to make it compile.

**Comment by mbowerman** [comment]
I was able to modify the bnd, packageinfo, and build.gradle files to get the calendar to successfully deploy. Unfortunately, that does not seem to have resolved the problem; I am still unable to access the calendar portlet from the add portlet panel. I'm not really sure what I should be looking for at this point...

**Comment by marcellustavares** [comment]
ok, will take a look at this @mbowerman, thanks for the help!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@brandizzi, please send the Javadocs separetly to @rbohl

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1528. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/99ed3e9~2...99ed3e9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
