### PR TITLE
Lps 60202

### PR DESCRIPTION
**Pull request by ligasm**
Hi @marcellustavares 

resending you the PR.

https://github.com/brunobasto/liferay-portal/pull/602

cc @brunobasto @jbalsas

### CODE REVIEW

**Comment by ligasm** [comment]
Hi @jbalsas

I looked at the image cropper portlet and from the code perspective there is no need to change anything. I just updated the dependency to the latest version. 

I tested it and it worked fine.

**Comment by marcellustavares** [comment]
hey @ligasm, I don't think we can increment the major version at this point. Is there other way to implement this?

Thanks

**Comment by jbalsas** [comment]
Hey @marcellustavares, I haven't looked at this, but `soy-bridge` was never released and the only real consumer is `image-editor-web`, so I think we could fight to get this in if necessary. (I leave it to your judgement, since I haven't been really involved in this part)  

@ligasm, so we would only need to update if we were owerwriting the `render` method of `SoyPortlet`?

**Comment by ligasm** [comment]
Hi @marcellustavares & @jbalsas

The render method  is the reason I incremented the major version. It was used in a bad way and we should indicated it somehow. 

Basically from the portlet specification you should never overwrite the render method. The doView, doEdit ... method should be used instead. This overwrite is reserved for framework related stuff as we do in SoyPortlet. 

The problem with overwriting the render method is that you loosing control over the order of execution. I our case the we need to set the template into the request as a first action in the render method and nothing should normally happen before. Then we want to set the path and after that we don't care so much if  super.render is called eventually.

This works fine when the MVCRednerAction patter is used but the HelloSoyPortlt breaks it.

The intend here is to force the user of SoyPortlet to do the right thing and the doRender (maybe not best name) method is here to provide a safe way to do so.

**Comment by jbalsas** [comment]
Sounds good to me!

**Comment by ligasm** [comment]
Hi guys 

what with this?

**Comment by jbalsas** [comment]
Hi @ligasm!

We're drawing our lines of work for the future, and moving forward with our Soy support is in there, so we'll be coming back to this as soon as we re-start executing those ideas.

Thanks!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/704. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
