### PR TITLE
DDMFormValuesToPropertiesConverterTest Integer behaviour

### PR DESCRIPTION
**Pull request by cgoncas**
Hi @marcellustavares,

I only want to ckeck with you if it is correct that the DDMFormValuesToPropertiesConverter returns 0 as Integer when the input value is not a valid Integer, for example '42f'.

Thanks in advance,

### CODE REVIEW

**Comment by marcellustavares** [comment]
hey @cgoncas, I think the behavior is right, do you want me to push this to master?

**Comment by cgoncas** [comment]
Hi @marcellustavares ,

   Yeah, I think is a good idea register the new test, so there are no more doubts about that behaviour.

Thanks

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43441. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
