### PR TITLE
LPS-67899 passing serviceContext to PollsChoice

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Thanks @linolaoj, I guess these errors are not related.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42907. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
