### PR TITLE
master-qa-27530

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-27530

### CODE REVIEW

**Comment by ctampoya** [comment]
@marcellustavares I fixed the SF issue that was happening with the Forms testcase.

**Comment by marcellustavares** [comment]
Thx @ctampoya

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43051. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/10d986d~2...10d986d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
