### PR TITLE
LPS-55433 You can't share the same package between two bundles, so the test classes should have another package

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @marcellustavares,

I had to move the test packages to one finished with "test". In OSGi you can't share the same package between two bundles.

Now there are others fails, but I think that they are related with the implementation, I think, but I am not sure. If you now something more, please, tell me.

Thanks!!!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
You can check the fails here:

https://github.com/cgoncas/liferay-portal/pull/125

**Comment by marcellustavares** [comment]
Thanks @cgoncas!

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2270. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
