### PR TITLE
LPS-65647 Unable to publish and save web content draft after upgrading from 6.x

### PR DESCRIPTION
**Pull request by topolik**
Hi Marcellus,

**UPDATE**: so it seems it works! Looks like I had some mix of upgraded / non-upgraded data in DB. Still I'd be luckier if anybody could verify it and probably it deserves @juliocamarero's review

---

I fixed the permission resource actions by reverting original solution for LPS-63664 and creating the Journal DDM things during UpgradeJournal.

On top I placed the commit from your pull https://github.com/jkappler/liferay-portal/pull/105

Upgrade works, but when I start portal I get SQL exceptions.

Without your commit upgrade works and portal is started. But the WCM draft still cannot be saved.

Can you please take a look? 

Thanks!

https://issues.liferay.com/browse/LPS-65647

/cc @juliocamarero @csierra

### CODE REVIEW

**Comment by jkappler** [comment]
@topolik, I tested it and it worked perfectly 👍

**Comment by topolik** [comment]
thanks @jkappler!

**Comment by topolik** [comment]
@marcellustavares, may I ask you to review your code, if it's still the one you want, I'm not sure how finished it is, and then send to @juliocamarero for review? Thank you.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/4165. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/3691915~1...3691915) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @topolik!!

**Pull request closed without merging**
