### PR TITLE
LPS-69574 Inconsistent Search Results With Custom Expando Fields

### PR DESCRIPTION
**Pull request by arboliveira**
Hi @marcellustavares!

Please review changes made to `ExpandoBridgeIndexerImpl` (`portal-impl`) and `BaseIndexer` (`portal-kernel`) in order to distinguish between `text` and `keyword` fields, using different analyzers for each index type like DDM does. Also, please validate the assertions we're enforcing in the new `ExpandoSearchTest` (`portal-search-test`).

Note: must regen `system.packages.extra.mf` -- not sending in this PR as you'd probably get a merge conflict with master by the time you get to review   😆 

Thanks!

Author: @BryanEngler
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-69574

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

Apparently random startup crashes under JBoss and Wildfly.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/arboliveira/liferay-portal/pull/191. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
