### PR TITLE
LPS-64201 gradlew buildLang

### PR DESCRIPTION
**Pull request by brandizzi**
Hey Marcellus!

This is the first part of the changes Ed asked for. I will be sending some more later.

Thanks!

### CODE REVIEW

**Comment by marcellustavares** [comment]
@brandizzi, I'm assuming we don't have to backport this to 7.0.x right?

**Comment by brandizzi** [comment]
Yes, we do not have to backport this.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37616. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/dac7fef~1...dac7fef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
