### PR TITLE
LPS-58771 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
cc @xbrianlee

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:reopen

Looking into this test failure...

**Comment by marcellustavares** [comment]
Rafael Prax took this pull for review.

**Pull request closed without merging**
