### PR TITLE
LPS-67894 SF - Factoring to make the logic traceable.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@brandizzi, are these POSHI regressions? Are we safe?

Thanks

**Comment by daledotshan** [comment]
Hey Marcellus,
Thanks for helping review this pull request? Could you  please review this ticket as high priority? we have a ee cusotmer are waiting for this fix.

@brandizzi, could you please answer Marcellus question?
Thanks,
Dale

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/298. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/e1738a4~1...e1738a4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
