### PR TITLE
LPS-48609 Fixing more fields

### PR DESCRIPTION
**Pull request by pablocp**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Hey @pablocp, how come we're duplicating everything? shouldn't we pass readOnly true or false to the taglibs?

Not merging. 

Thanks

**Comment by pablocp** [comment]
The value of the readonly attribute is not important. Its presence already makes the field to be not editable, so passing readonly=false is the same as readonly=true (also the same as readonly="readonly" or readonly="foo").

**Comment by juangon** [comment]
Yes @pablocp  but what if adding a variable for storing readonly="readonly" only if it should be set like that?

<#include "../init.ftl">
<@aui["field-wrapper"] data=data>
<#assign readonlyTxt = "">

<#if fieldStructure.readOnly?? && (fieldStructure.readOnly == "true")>
<#assign readonlyTxt = "readonly='readonly'">
</#if>

<@aui.input cssClass=cssClass dir=requestedLanguageDir helpMessage=escape(fieldStructure.tip) label=escape(label) name=namespacedFieldName readonlyTxt type="text" value=fieldValue>
<#if required>
<@aui.validator name="required" />
</#if>
</@aui.input>
</#if>
${fieldStructure.children}
</@>

**Comment by pablocp** [comment]
It is not a valid freemarker syntax. When a tag starts with "<@", freemarker expects all attributes to be passed as "attributeName=attributeValue", so you can't just leave "readOnlyTxt" without an assignment (even if its value is itself an assignment).

**Comment by juangon** [comment]
Hi @pablocp. This wasn't a real script, just an idea of how to implement. Didn't check myself, but idea should work, isn't it? Thanks!

**Pull request closed without merging**
