### PR TITLE
LPS-63925 Fix wrong dir

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1265. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/6dbe85c~1...6dbe85c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
