### PR TITLE
LPS-54277

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by bejondshao** [comment]
Hey @marcellustavares , would you take some time to review this?

Thanks

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27944. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
