### PR TITLE
LPS-61568 Copy to clipboard and LPS-61740 Form Publish screen is empty resolution

### PR DESCRIPTION
**Pull request by fernandosouza**
@marcellustavares this PR also contains the resolution for this issue [https://issues.liferay.com/browse/LPS-61740]. Both tickets are linked.

### CODE REVIEW

**Comment by fernandosouza** [comment]
@marcellustavares this PR also contains the resolution for this issue [https://issues.liferay.com/browse/LPS-61740]. Both tickets are linked.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/jonmak08/liferay-portal/pull/1423. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/c768819~4...c768819) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/383. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/c768819~4...c768819) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
