### PR TITLE
LPS-62564

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @marcellustavares,

Attached is an update for http://issues.liferay.com/browse/LPS-62564.

We had to revert these two commits by @inacionery  since they cause regressions and do not conform to the Lexicon standards of the secondary navbar.  I spoke with @natecavanaugh regarding this and said we should revert those changes to match all the other portlets.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by inacionery** [comment]
Hi @jonmak08,

This change happened for Ivan Morote's request. He specified that should be a nav-tab not a nav-bar. This is the Lexicon standard's, no? (http://liferay.github.io/lexicon/content/nav-tabs/)

Thanks.

/cc @marcellustavares

**Comment by jonmak08** [comment]
Hey @inacionery,

In looking at the Lexion guidelines (https://liferayeng.slack.com/?redir=%2Ffiles-pri%2FT03BTCQAJ-F07F44JNS%2Flexicon_-_guidelines_-_draft_-_v04.compressed.pdf), you will see in section 3.2 regarding the navigation structure and flow and 1st and 2nd level navigations, that we do not have any tabs in this section.  Navigation bars are what is used instead.

Please let me know if you have any questions. Thanks!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Hey @jonmak08, I've talked to Ivan Morote and he said we should keep the tabs for now. He'll be updating the guidelines to cover the Workflow scenarion.

Thanks a lot!

**Comment by jonmak08** [comment]
Hey @marcellustavares,

Sounds good, I just spoke with @natecavanaugh, about this and he said we should go with what Ivan stated.

Can we have @inacionery take a look at https://issues.liferay.com/browse/LPS-62564 since this issue is caused by his changes?

Please let me know if you have any questions. Thanks!

**Comment by marcellustavares** [comment]
hey @jonmak08, thx. The LPS is NLR.

**Comment by marcellustavares** [comment]
I've just updated the ticket, cc @vicnate5.

**Pull request closed without merging**
