### PR TITLE
LPS-62558 Do not inject portal resources by default

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
hey @marcellustavares @rafaprax 

this should pass all the tests now (as seen here https://github.com/csierra/liferay-portal/pull/182#issuecomment-183078149 I did not want to disturb)

If you prefer this approach too please push it to Brian...

Thx.

**Comment by marcellustavares** [comment]
Thx dude, will push it fwd tomorrow.

**Comment by csierra** [comment]
hey @marcellustavares!

did you have a chance to look at this?

Is there anything I can do to help?

Bests!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/36109.

**Pull request closed without merging**
