### PR TITLE
LPS-67325 Adds dependency to last version

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc\ @juliocamarero @marianoalvarosaiz

**Comment by rafaprax** [comment]
Hey @ealonso, @marcellustavares is on vacation. So, could you please send this pr to me? Thx

**Comment by juliocamarero** [comment]
https://github.com/rafaprax/liferay-portal/pull/127

**Comment by marcellustavares** [comment]
Closed as this was sent to @rafaprax.

**Pull request closed without merging**
