### PR TITLE
LPS-57481 Add permission check when executing dynamic data list display portlet

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest @leoadb - I had to reset the jenkins servers.

**Comment by leoadb** [comment]
@marcellustavares it seems not related with what i did

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29281. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/1d7de11~2...1d7de11) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
