### PR TITLE
master-vw-20

### PR DESCRIPTION
**Pull request by vicnate5**
Test fixes for https://github.com/marcellustavares/liferay-portal/pull/809. The PR tester test for DDL will fail even with these fixes due to https://issues.liferay.com/browse/LPS-58839

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchiu** [comment]
@vicnate5 @marcellustavares 
You can just send this straight to BChan. No need to go through me. I've already reviewed Clarissa and Victor's changes.

**Comment by marcellustavares** [comment]
got it, thx @brianchiu

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/25. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/a98d941~4...a98d941) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
