### PR TITLE
LPS-68288 Save settings on Field value change

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
cc @vicnate5

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44221. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
