### PR TITLE
LPS-66409 User cannot view My Workflow Tasks with permissions

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
There seems to be an issue on the PR tester causing these tests to fail. The tests are failing during the `setup` step.

**Comment by vicnate5** [comment]
@rafaprax The user can access the workflow asset in my workflow tasks with this fix. However, the user with Site Admin and Site Content Reviewer cannot "Assign to Me" or "Assign to.."

assignmentpermissions

**Comment by rafaprax** [comment]
@vicnate5 I'll check and fix this. Thx

**Pull request closed without merging**
