### PR TITLE
LPS-64428 Add Staging tests to DDMDataProviderInstance

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Awesome @rafaprax, thx :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37875. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/e8eb5a5~1...e8eb5a5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
