### PR TITLE
LPS-66426 Add tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41565. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/2f38a09~4...2f38a09) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@leoadb, I've just removed the propagation of this first pull to make it smaller, let's do the remaining in the second pull.

Thanks

**Pull request closed without merging**
