### PR TITLE
LPS-63341 Fix dependencys

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36441. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/31513a1~1...31513a1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
