### PR TITLE
LPS-97552

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @marcellustavarez, @fcodias

If possible, I'd prefer to avoid adding extra parameters to the URLs, they're
ugly enough as they're :-)

So, I've changed things slightly; instead of adding an extra parameter to to
URL, I've added a new `data-analytics-file-entry-id` attribute, which should be
added to all tracked `a`'s.

Let me know what do you think of this approach.  If you're ok with it, feel free
to send it to Brian directly.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
thanks @adolfopa!

**Comment by marcellustavares** [comment]
Just started reviewing :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/fcodias/liferay-portal/pull/8.

**Pull request closed without merging**
