### PR TITLE
LRAC-10822 merge module into analytics-batch-export-import

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:reevaluate:1357401_1189

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
