### PR TITLE
LPS-71299 Fix issues

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares This one has commits for the previous PR due to testing purpose. Only the commits tagged with LPS-71299 are needed. Please remove the others before sending to Brian. Thanks!

**Comment by marcellustavares** [comment]
got it, thx @leoadb

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/178. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
