### PR TITLE
LPS-65802 Avoid add an empty condition.

### PR DESCRIPTION
**Pull request by inacionery**
/cc @topolik

### CODE REVIEW

**Comment by topolik** [comment]
Thanks a lot @inacionery !

**Comment by marcellustavares** [comment]
Thanks a lot @inacionery @topolik!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41252. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
