### PR TITLE
LPS-71916

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/126. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
