### PR TITLE
LPS-58575 Use Bundle by default but allow overriding

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
/cc @rafaprax @marcellustavares 

hey guys... this is the way I would do it... in the end it is doing the same thing @rafaprax changed in his pull... but allowing further overriding by registering a custom _ResourceBundleLoader_ for the corresponding `bundle.symbolic.name`.

Bests.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Awesome @csierra, thx a lot!

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35451. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
