### PR TITLE
LRAC-5823 analytics-message-sender-api baseline

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @riccardo-ferrari

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:forward

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
Just started reviewing :)

**Comment by marcellustavares** [comment]
resent to https://github.com/marcellustavares/liferay-portal/pull/1954

**Pull request closed without merging**
