### PR TITLE
LPS-56795 - SF.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Beautiful @natocesarrego! Almost dropped one tear :joy:

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28547. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/2f12b6e~1...2f12b6e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Nice! :) Thanks.

**Pull request closed without merging**
