### PR TITLE
LPS-57666

### PR DESCRIPTION
**Pull request by samuelkong**
cc @daviddotzhang

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
ci:retest

**Comment by daviddotzhang** [comment]
@marcellustavares  @samuelkong 

As the customer is in hurry, they want a permanent fix ,could you kindly have a look at it ?

Thanks in advance

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29390. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @samuelkong, @daviddotzhang :)

**Pull request closed without merging**
