### PR TITLE
LPS-66815 Create form browser for browsing forms

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @marcellustavares, this would be the form browser that I mentioned to you a couple of weeks ago and that we are using in AT. The idea is that in future releases we will use the one from DDL and delete the temporary one.

Please let me know what you think. It has only the basic view (list) and basic ordering.

If change is needed, just let me know. Thanks!!!

cc// @ealonso

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @jkappler! very cool :) @vicnate we will need a poshi test for this.

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/445. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
