### PR TITLE
LPS-64066 Apply lexicon to configuration page

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37547. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/5a94732~1...5a94732) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
