### PR TITLE
LPS-56848 Move to internal package

### PR DESCRIPTION
**Pull request by leoadb**
[Review on Reviewable](https://reviewable.io/reviews/marcellustavares/liferay-portal/610)

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
@marcellustavares , JournalContentImpl uses StopWatch which is a class from commons lang library.

**Comment by marcellustavares** [comment]
got it, thx!

**Comment by marcellustavares** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/marcellustavares/liferay-portal/610)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/627. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/2980c2f~2...2980c2f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
