### PR TITLE
LPS-60722 Extract aui:translation-manager taglib to ddm:translation-manager

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Marcellus,

I made the changes to the xmls in 071c783 and then ran both build taglib tasks in 0aa717b.

Please let me know if there are any other issues.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mjbradford89, I assume that if ddm taglibs are autogenerated, we should not merge the base class. That would only make sense for the case where we want to transform an autogenerated to a static one.

Check how the other autogenerated ones are keeping the base class inside ddm https://github.com/liferay/liferay-portal/tree/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-taglib/src/main/java/com/liferay/dynamic/data/mapping/taglib/servlet/taglib

I assume that's how @marcellustavares would want it. Sorry for the confusion! :(

**Comment by mjbradford89** [comment]
@jbalsas ah I see, I removed that commit. thanks!

**Comment by mjbradford89** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Pull request forwarded to https://github.com/leoadb/liferay-portal/pull/160. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
