### PR TITLE
LPS-65802 Fix invalid relational operator

### PR DESCRIPTION
**Pull request by inacionery**
@topolik,
Oracle, DB2, SYBase doesn't support 
`SELECT DDMStructure.structureId FROM DDMStructure INNER JOIN ResourcePermission ON  ((....)  OR (0))`
 it must be 
`SELECT DDMStructure.structureId FROM DDMStructure INNER JOIN ResourcePermission ON  ((....)  OR (0 <> 0))`

### CODE REVIEW

**Comment by marcellustavares** [comment]
@inacionery, are these issues related? I guess not right?

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41356. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
They aren't related

**Pull request closed without merging**
