### PR TITLE
[TECHNICAL-SUPPORT]LPS-60127 Value in non localizable field disappear after updating translation

### PR DESCRIPTION
**Pull request by zsolah**
Hello Marcellus,

I have created a new test to justify my changes.
On branch when adding a new translation, on the translation edit form nonLocalizable fields are disabled, and they are not represented in the _fieldsDisplay values when adding/editing translation. Without the change in DDMImpl, the existingFields _fieldsDisplay is overwritten with the newFields _fieldsDisplay, which can result a wrong merge. (Later making repetition count 0, for non localizable fields at content xml creation) 

If I got it right, the isPrivate() can only be true for the _fieldsDisplay field, which is a meta-data, listing the non disabled displayed fields. Please correct me if I'm wrong.

Regards,
Zsolt

### CODE REVIEW

**Comment by zsolah** [comment]
ci:retest

**Comment by marcellustavares** [comment]
It should be a random failure @zsolah, thanks for the fix :)

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31842. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
