### PR TITLE
LPS-55620

### PR DESCRIPTION
**Pull request by jcampoy**
Hi Marcellus, could you review this fix? Let me know if you have any question, thx

### CODE REVIEW

**Comment by jcampoy** [comment]
Hi Marcellus, this issue is for technical support, could you take a look?

Thx!

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29843. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
