### PR TITLE
LPS-68209 trim to check if string is empty

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@linolaoj you forget the unit test. I'll add this time.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43678. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/44a6dbc~1...44a6dbc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
