### PR TITLE
LPS-60626

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32495. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/841f166~1...841f166) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @yuhai :+1:

**Comment by yuhai** [comment]
Hi Marcellus,

Thanks for reviewing the fix.

I check your change regarding the fix. I want to explain the current change will break LPS-58996. Please check the original fix explantion regarding LPS-60626.

LPS-60626 was caused by LPS-58996. Because when create document type, we will create dlfileentrytype and ddmstructure in the same time. Please refer to the logic DLFileEntryTypeLocalServiceImpl.addFileEntryType() { 96-137 lines}, it also create related data in ddmstructurelink table. So when delete dlfileentrytype, we should also delete related data in ddmstructurelink and ddmstructure table. This is LPS-58996 fix logic.

However, when create Data Definitions, we will only create ddmstructure. Please refer to AddStructureMVCActionCommand.addStructure(). When create Dynamic Data Lists(DDLRecordSet), we need to choose Data Definitions, after saving Dynamic Data Lists, The related data also creates in ddmstructurelink table. So if DDMStructure are created by adding Data Definitions, we should judge whether Data Definitions(ddmstructure) is used by Dynamic Data Lists(DDLRecordSet). If using, we shouldn't allow to delete.

For var classNameDDLRecordSet definion, I refer to BaseDDMServiceTestCase.java. 
```
	protected static final String DDL_RECORD_CLASS_NAME =
		"com.liferay.dynamic.data.lists.model.DDLRecord";
```

Thanks,
Hai

**Pull request closed without merging**
