### PR TITLE
LPS-65430 Add test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@leoadb, could you document this somewhere in our tech debts docs? Or please create a JIRA ticket with a story to move the DDLRecord permissions to the DDLRecord model?

We need to link with this fix so we can remember.

Thanks

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39365. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
