### PR TITLE
LPS-56232 Create DDMTemplateLink during upgrade - forgotten by LPS-55110

### PR DESCRIPTION
**Pull request by achaparro**
Hey @marcellustavares,

Please, check if you forgot something else in https://issues.liferay.com/browse/LPS-55110 since I don't know the new funcionality added by that LPS.

Thanks.
PS: @epgarcia

### CODE REVIEW

**Comment by marcellustavares** [comment]
Thanks @achaparro!

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27330. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Thank you @marcellustavares

Have a good week!
Cheers!

**Pull request closed without merging**
