### PR TITLE
LPS-62024 Fix test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34834. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/61bdbc4~3...61bdbc4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
