### PR TITLE
LPS-56566 usage example of Transformer in the DDL service module.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
