### PR TITLE
LPS-58580 Apply lexicon pattern to action oprions

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/24. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/89da0ec~3...89da0ec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
