### PR TITLE
LPS-66174 Templates and Structures cannot be accessed after upgrade from 7.0 CE GA1 to 7.0 DE / 7.0 CE GA2

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40371. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/96aec42~1...96aec42) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
