### PR TITLE
Applying Lexicon pattern to the Dynamic Template search field

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@fernandosouza, CI is not triggering for you. Can you make sure to add Liferay org in your profile. Please see https://help.github.com/articles/publicizing-or-hiding-organization-membership/

**Comment by fernandosouza** [comment]
Done @marcellustavares. Now it's public. https://github.com/orgs/liferay/people?utf8=✓&query=Fernando

**Comment by marcellustavares** [comment]
Thx @fernandosouza

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/186. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
