### PR TITLE
[TECH SUPPORT] LPS-66532 NoSuchEntryException for custom workflow when approving from a Scheduled status

### PR DESCRIPTION
**Pull request by giros**
Hi Marcellus,

Please review. See https://issues.liferay.com/browse/LPS-66532 for details.

Regards,
G

### CODE REVIEW

**Comment by giros** [comment]
Hi @marcellustavares,

Will you be able to review this sometime in the near future?

Thanks,
G

**Comment by marcellustavares** [comment]
@giros, is there a way to create a test case for this?

**Comment by giros** [comment]
Hi @marcellustavares,

I'm not sure, since the use case involves using a custom workflow definition. Do you insist creating a test? :) The fix is pretty much the same as https://issues.liferay.com/browse/LPS-23329 did for Expired status.

Regards,
G

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41338. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Ok @giros, I flagged the LPS as `fw_test_not_need`.

**Comment by giros** [comment]
Thank you @marcellustavares!

**Pull request closed without merging**
