### PR TITLE
LPS-91023 Check if the Shared Form belongs to a group which has analytics tracking enabled

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
Just started reviewing :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/240.

**Pull request closed without merging**
