### PR TITLE
LPS-59071 add Add template button to the template browser view

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
hey @marcellustavares, it seems that CI server keeps failing since yesterday, nothing to deal with the pull

**Comment by marcellustavares** [comment]
Ok, Thanks @pavel-savinov :+1:

**Comment by leoadb** [comment]
@marcellustavares I got this. I will review and test it. Please close this PR.

**Comment by marcellustavares** [comment]
Thanks! closing PR per @leoadb comment.

**Pull request closed without merging**
