### PR TITLE
[TECHNICAL-SUPPORT] LPS-69836

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@jonathanmccann, some workflow tests are failing after this change. Could you please double check? 

if you have any questions, you can ping @vicnate5.

Thanks

**Comment by marcellustavares** [comment]
@jonathanmccann, any updates on this?

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@marcellustavares I'll take a look at the test failures and let you know what I find.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@marcellustavares I believe I have resolved the issues with the fix. Please let me know if you have any questions.

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/1174. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/366c95d~1...366c95d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
