### PR TITLE
LPS-88495

### PR DESCRIPTION
**Pull request by samuelkong**
cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
Thanks @samuelkong

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66367. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
