### PR TITLE
LPS-65453 Add upgrade schema to include the tables KaleoTimer and KaleoTimerInstanceToken

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@rafaprax, test failures

**Comment by vicnate5** [comment]
@marcellustavares Workflow failure appears to be unrelated as it also occurs on this pull to BChan: https://github.com/brianchandotcom/liferay-portal/pull/39415

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@rafaprax,

why v1_1_0.UpgradeWorkflowContext would need to care about renamePortalJavaClassNames that just happened from 6.2 -> 7.0?

It's confusing. the kernel package rename should be just part of the the of the last step.

could you please resend this?

Thanks

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39451. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/9adddb2~5...9adddb2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
