### PR TITLE
LPS-58460 Apply style to ddlRecordSet edit page

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30038. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/54ad951~3...54ad951) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
