### PR TITLE
master-vw-224

### PR DESCRIPTION
**Pull request by vicnate5**
It seems this pull https://github.com/vicnate5/liferay-portal/pull/224 has a regression on it, that is why the test failed. The user cannot add a Radio field.

### CODE REVIEW

**Comment by vicnate5** [comment]
JAVA_SCRIPT_ERROR: TypeError: a is undefined [http://localhost:9080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7000&t=1456505414929&/o/dynamic-data-mapping-type-text/text.soy.js&/o/dynamic-data-mapping-type-radio/radio_field.js&/o/dynamic-data-mapping-type-radio/radio.soy.js&/o/dynamic-data-mapping-type-select/select_field.js&/o/dynamic-data-mapping-type-select/select.soy.js&/o/dynamic-data-mapping-type-date/date_field.js&/o/dynamic-data-mapping-type-date/date.soy.js&/o/dynamic-data-mapping-type-validation/validation_field.js&/o/dynamic-data-mapping-form-renderer/js/field.js&/o/dynamic-data-mapping-type-checkbox/checkbox_field.js&/o/dynamic-data-lists-form-web/admin/js/form_builder.js&/o/dynamic-data-lists-form-web/admin/js/form_definition_serializer.js&/o/dynamic-data-lists-form-web/admin/js/form_layout_serializer.js&/o/dynamic-data-lists-form-web/admin/js/form_portlet.js&/o/frontend-js-web/aui/model/model-min.js&/o/frontend-js-web/aui/model-list/model-list-min.js&/o/frontend-js-web/aui/datatable-core/datatable-core-min.js:40]

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/470. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/7f79aaa~4...7f79aaa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
thx @vicnate5!

**Pull request closed without merging**
