### PR TITLE
LPS-63931 Remove static call

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by vicnate5** [comment]
Unrelated Failures.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1254. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/a49f6b5~3...a49f6b5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
