### PR TITLE
Lps 83612

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest:relevant

**Comment by marcellustavares** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/80. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
hey @SamZiemer, could you please send the pull directly to @jeyvison next time? He's the primary reviewer for DDM.

Thanks

**Pull request closed without merging**
