### PR TITLE
LPS-62755

### PR DESCRIPTION
**Pull request by jcampoy**
cc/ @juliocamarero

### CODE REVIEW

**Comment by marcellustavares** [comment]
Also @jcampoy, could you add tests for this?

**Comment by jcampoy** [comment]
I will try to add tests tomorrow. 
Thanks!

**Comment by marcellustavares** [comment]
Awesome, thanks @jcampoy

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35580. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/b0c9276~1...b0c9276) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
