### PR TITLE
LPS-67505 Add unit test

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43050. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/2414e40~1...2414e40) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
