### PR TITLE
LPS-68687 Tests for CalendarResourceUtil (including current issue)

### PR DESCRIPTION
**Pull request by brandizzi**
cc @natocesarrego @sherlyliu

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44873. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/09f6c0a~1...09f6c0a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/341. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/09f6c0a~1...09f6c0a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
