### PR TITLE
LPS-65802 Site admin cannot use data definitions without explicit permissions

### PR DESCRIPTION
**Pull request by topolik**
Hi Marcellus,

I reverted the fix from sub-select to the original JOIN. It can have different SQL execution plan with (for me) unknown impacts on performance. Also the code can be now vulnerable if the caller use OR.

Instead I modified the JOIN and for group admin I join default owner ResourcePermission record.

The tests were fine, as far as I can tell.  But please can you double check?

Also, feel free to remove the original solution and the revert commits before sending to Brian.

Thanks!

### CODE REVIEW

**Comment by marcellustavares** [comment]
Awesome @topolik, thanks for the help! @inacionery could you please double check and let me know if I can push to Brian?

Thanks

**Comment by inacionery** [comment]
@marcellustavares there is an issue in the query! I'll send a PR on this fix.

**Comment by inacionery** [comment]
Done! https://github.com/marcellustavares/liferay-portal/pull/1518

**Comment by marcellustavares** [comment]
Sent final revision to https://github.com/brianchandotcom/liferay-portal/pull/41252

**Pull request closed without merging**
