### PR TITLE
[TS] LPS-71323 Display the editor user instead of the creator

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-71323](https://issues.liferay.com/browse/LPS-71323)

Hi Marcellus,

As per [Tibor Lipusz's request](https://github.com/lipusz/liferay-portal/pull/171#event-1028346452) I'm sending this to you directly. Please review my changes.

*Issue:* DDLRecord type of assets always display the creator user as author while other type of assets display the editor user.

*Cause:* There is one DDLRecord for each new record, plus DDLRecordVersions for each modification (version) of it. DDLRecordAssetRenderer queries the user from DDLRecord, which refers to the creator, while the actual editor user is stored in DDLRecordVersions.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:reopen

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Those errors look unrelated to my fix. Anyway, I have updated my branch.

**Comment by istvansajtos** [comment]
ci:retest

**Comment by marcellustavares** [comment]
It does not seem related @istvansajtos, thx for the fix.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48158. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
