### PR TITLE
LPS-65450 Add integration tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks for the test @rafaprax :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39364. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/26e6d4f~1...26e6d4f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
