### PR TITLE
LPS-71219

### PR DESCRIPTION
**Pull request by matethurzo**
@marcellustavares this is changing the SMR framework from inheritance approach to composition. This is the DDL related part, but I've changed a few things in there I wanted to you to take a look on it.

If you have any questions please let me know

### CODE REVIEW

**Comment by matethurzo** [comment]
@marcellustavares rebased and pushed again to update to the latest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
hey @matethurzo, I'm totally ok with your changes but  this new API going to be release in jun/july? I'm concerned about this change because we're planing a release by this date.

will we need to rollback?

Thanks

**Comment by matethurzo** [comment]
@marcellustavares you are right, let me sort this out with Mike and Jose and I'll get back to you. Initially we didn't want to release but now we might be forced to.

Thx.

**Comment by marcellustavares** [comment]
thx @matethurzo!

**Pull request closed without merging**
