### PR TITLE
[TECHNICAL-SUPPORT] LPS-69984

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @marcellustavares,

I'm not 100% sure about this one. It seems like it could be a permissioning issue rather than a bug, so I was hoping you would know better.

/cc @SGM3

### CODE REVIEW

**Comment by SGM3** [comment]
Just to point out, if it is a permissioning issue, the Image selector for HtmlField is bypassing the permission the same way.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/285. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
thanks @jonathanmccann @SGM3

**Pull request closed without merging**
