### PR TITLE
LPS-60427 An anonymous user can vote only once

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiosanchez** [comment]
Hi Marcellus.
This solution is to apply the way it worked in 6.0.x.
In 6.0.x, as there was a null userId, a new userId was created.
In 6.2 the userId takes the default user and because of that any other anonymous user can not vote.
With this solution, I try to get back the 6.0.x functionality, but as in that version it creates userIds without an entry in the User_ table. Maybe another approach is better.

**Comment by marcellustavares** [comment]
Hey @sergiosanchez, I'm not sure what should be the business requirements for this. Should we allow guest users to vote or not?

If we allow I tend to think we should use defaultUser and remove the random userId generation and then remove the check for defaultUser. If we we won't allow the vote, then your fix it's fine if we remove the random generation id block.

We might be able to allow one vote restriction for registered users only otherwise we should use cookies or other hack.

What do you think @sergiogonzalez?

Regards,

**Comment by sergiosanchez** [comment]
Hi @marcellustavares 
Your question is the right one. Should the anonymous users allowed to vote? Who can give us an answer to this behaviour?

**Comment by sergiosanchez** [comment]
In past verions it was possible (6.0.x) 
In 6.2.x it is still possible to give to the Guest role the permission to Vote.

If we re-enable the past version, assigning the votes to the guest user won't work either because there is a unique index with (userId, questionId), so we need to figure out another solution:
- use like a 6.0.x a random userId
- make it more powerful, like posting anonymous comments

If we restrict the votes for anonymous users, I guess we should change the UI to not allow to enable Vote for the Guest role. Also, I should tell the customer that this feature is lost.

**Comment by sergiogonzalez** [comment]
Hey guys,

I'm not sure about what is the expected behaviour here, so maybe we should check with PM to see what is expected.

Other thing that we could do too is to follow an approach similar to what we have for guest comments. So we allow the people to vote but first they need to provide an email account (and we create a inactive account under the hood) and then, once they have voted, we can ask them if they want to activate the account or not. By doing this we no longer need the randomness in the user, but this won't allow to vote if the creation of accounts is disabled in the portal.

Just my 2 cts...

**Comment by sergiosanchez** [comment]
Ok, then. In this case, as this is not very clear what to do I will escalate the LPS ticket and you guys decide on how the product should behave and what the best solution is.
Is that OK?

**Comment by marcellustavares** [comment]
That's a good idea @sergiogonzalez, we can talk to Ed about that.

Thanks @sergiosanchez! I'll close this PR for now so we can discuss this matter.

Regards,

**Pull request closed without merging**
