### PR TITLE
LPS-65569 Show success message

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/531. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
