### PR TITLE
LPS-67815

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
information from hai
When update ddmcontent, we should use completed fields (including parentStructure fields) to update. So that it won't lose parentStructure's fields. For DDMStructure table, it only includes own fields, and it should use original getDDMForm(long) method.

**Comment by daledotshan** [comment]
Hey marcellus,
This fix is for a ee customer please help to review it

Thanks

**Comment by marcellustavares** [comment]
hey @daledotshan, we have some failing tests on this pull. Are they related?

Thanks

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/241. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
I think we're safe, thanks @daledotshan @yuhai!

**Pull request closed without merging**
