### PR TITLE
LPS-55026 Removing unused files

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
beautiful @brandizzi  :heart_eyes:

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27552. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
