### PR TITLE
CSS style in autofill rule

### PR DESCRIPTION
**Pull request by diogo-lins**
\cc @leoadb @rafaprax @thiago-rocha 

@marcellustavares Here are all commits related with field set and auto fill rule :D
Please run the 'buildLang'  I performed in my machine but this didn't work.

### CODE REVIEW

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/299. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
