### PR TITLE
LPS-70091 remove unclosed parenthesis

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
it's good @pavel-savinov :) thx

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46127. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
