### PR TITLE
LPS-56447 Removed DDM dependency from HookHotDeployListener

### PR DESCRIPTION
**Pull request by pablocp**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
CI is not triggering @pablocp.

Please make sure to make the Liferay organization public, see https://help.github.com/articles/publicizing-or-hiding-organization-membership/ for details.

Thanks

**Comment by pablocp** [comment]
Done :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27515. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
