### PR TITLE
LPS-63938 Remove calls of DDMIndexerUtil

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by vicnate5** [comment]
Unrelated failures.

**Comment by vicnate5** [comment]
These failures look unrelated. But there was a failure on the Tomcat smoke test due to a console error:

`Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={groupId=0, STORAGE_TYPE=MEMORY_CLUSTERED, EXCEPTIONS_MAX_SIZE=0, JOB_NAME=com.liferay.asset.publisher.web.messaging.CheckAssetEntryMessageListener, GROUP_NAME=com.liferay.asset.publisher.web.messaging.CheckAssetEntryMessageListener, DESTINATION_NAME=liferay/scheduler_dispatch, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@febc6b, companyId=0}}`

Could this be related?

**Comment by brianchiu** [comment]
Here is the full error with some surrounding context (happens during portal startup)

```
     [exec] 17:36:43,774 INFO  [localhost-startStop-1][PluginPackageUtil:1004] Reading plugin package for the root context
     [exec] 17:36:44,716 INFO  [localhost-startStop-1][AutoDeployDir:146] Auto deploy scanner started for /opt/dev/projects/github/liferay-portal/bundles/deploy
     [exec] 17:36:45,649 INFO  [elasticsearch[Mister Hyde][clusterService#updateTask][T#1]][metadata:391] [Mister Hyde] [liferay-20202] creating index, cause [api], templates [], shards [1]/[0], mappings [LiferayDocumentType, KeywordQueryDocumentType, SpellCheckDocumentType]
     [exec] 17:36:45,708 INFO  [elasticsearch[Mister Hyde][clusterService#updateTask][T#1]][allocation:238] [Mister Hyde] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[liferay-20202][0]] ...]).
     [exec] 17:36:45,719 INFO  [elasticsearch[Mister Hyde][clusterService#updateTask][T#1]][metadata:317] [Mister Hyde] [liferay-20202] update_mapping [LiferayDocumentType]
     [exec] Loading bundleresource://257.fwk7317052/portlet.properties
     [exec] Loading bundleresource://181.fwk7317052/portlet.properties
     [exec] 17:36:48,133 INFO  [liferay/scheduler_dispatch-3][PluginPackageUtil:1268] Reloading repositories
     [exec] 17:36:48,147 ERROR [liferay/scheduler_dispatch-1][ParallelDestination:55] Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={groupId=0, STORAGE_TYPE=MEMORY_CLUSTERED, EXCEPTIONS_MAX_SIZE=0, JOB_NAME=com.liferay.asset.publisher.web.messaging.CheckAssetEntryMessageListener, GROUP_NAME=com.liferay.asset.publisher.web.messaging.CheckAssetEntryMessageListener, DESTINATION_NAME=liferay/scheduler_dispatch, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@febc6b, companyId=0}}
     [exec] com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
     [exec] 	at com.liferay.portal.kernel.scheduler.messaging.SchedulerEventMessageListenerWrapper.receive(SchedulerEventMessageListenerWrapper.java:65)
     [exec] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
     [exec] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
     [exec] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
     [exec] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: java.lang.NullPointerException
     [exec] 	at com.liferay.asset.publisher.web.util.AssetPublisherUtil.checkAssetEntries(AssetPublisherUtil.java:294)
     [exec] 	at com.liferay.asset.publisher.web.messaging.CheckAssetEntryMessageListener.doReceive(CheckAssetEntryMessageListener.java:60)
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
     [exec] 	... 6 more
     [exec] 17:36:48,421 INFO  [localhost-startStop-1][UpgradeProcess:80] Upgrading com.liferay.calendar.web.upgrade.v1_0_1.UpgradePortletPreferences
     [exec] INFO - Upgrading com.liferay.calendar.web.upgrade.v1_0_1.UpgradePortletPreferences
     [exec] 17:36:48,422 INFO  [localhost-startStop-1][LoggingTimer:70] Starting com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences
     [exec] INFO - Starting com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences
     [exec] 17:36:48,433 INFO  [localhost-startStop-1][LoggingTimer:38] Completed com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences in 11 ms
```

CC @vicnate5

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@inacionery, we need to investigate this further. There's some initialization issue.

Please resend.

**Pull request closed without merging**
