### PR TITLE
LPS-57666

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @daviddotzhang

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Hey @samuelkong, sorry I couldn't take this before. Is this still reproducible? If so, could you reopen the PR?

Thanks

**Comment by daviddotzhang** [comment]
@marcellustavares  @samuelkong 
just update to the latest master, hard code are still exist and issues can be reproduced.

**Comment by marcellustavares** [comment]
thx @daviddotzhang, could you resend the PR?

**Comment by samuelkong** [comment]
Sorry. I think I caused this problem. 
New PR sent. https://github.com/marcellustavares/liferay-portal/pull/716

**Pull request closed without merging**
