### PR TITLE
LPS-50660 -  Update latest version of DDMStructure

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
