### PR TITLE
[TECHNICAL REQUEST] LPS-67607 DDL spreadsheet displays "null" instead of blank when value is null text

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Marcellus,

I do not know if we need this, see my other pull request for ee-62x

https://github.com/marcellustavares/liferay-portal-ee/pull/176

Thank you in advance
Péter

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/35. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks for the fix @peterborkuti!

**Comment by natocesarrego** [comment]
Hi @peterborkuti,

Unfortunately, this fix will introduce another issue if it's merged to **ee-6.2.x** and a possible issue if it's merged to **master**. 😢 

Below I'll paste the code which the fix changes in order to explain better what I mean. Please see:
```
for (Field field : fields) {
	String fieldName = field.getName();
	String fieldType = field.getType();
	Object fieldValue = field.getValue(locale);

	if (fieldValue instanceof Date) {
		jsonObject.put(fieldName, ((Date)fieldValue).getTime());
	}
	else if (fieldType.equals(DDMFormFieldType.DOCUMENT_LIBRARY) &&
			 Validator.isNotNull(fieldValue)) {

		JSONObject fieldValueJSONObject =
			JSONFactoryUtil.createJSONObject(
				String.valueOf(fieldValue));

		String uuid = fieldValueJSONObject.getString("uuid");
		long groupId = fieldValueJSONObject.getLong("groupId");

		fieldValueJSONObject.put(
			"title", getFileEntryTitle(uuid, groupId));

		jsonObject.put(fieldName, fieldValueJSONObject.toString());
	}
	else if (fieldType.equals(DDMFormFieldType.LINK_TO_PAGE) &&
			 Validator.isNotNull(fieldValue)) {

		JSONObject fieldValueJSONObject =
			JSONFactoryUtil.createJSONObject(
				String.valueOf(fieldValue));

		long groupId = fieldValueJSONObject.getLong("groupId");
		boolean privateLayout = fieldValueJSONObject.getBoolean(
			"privateLayout");
		long layoutId = fieldValueJSONObject.getLong("layoutId");

		String layoutName = getLayoutName(
			groupId, privateLayout, layoutId,
			LanguageUtil.getLanguageId(locale));

		fieldValueJSONObject.put("name", layoutName);

		jsonObject.put(fieldName, fieldValueJSONObject.toString());
	}
	else if ((fieldType.equals(DDMFormFieldType.RADIO) ||
			  fieldType.equals(DDMFormFieldType.SELECT)) &&
			 Validator.isNotNull(fieldValue)) {

		fieldValue = JSONFactoryUtil.createJSONArray(
			String.valueOf(fieldValue));

		jsonObject.put(fieldName, (JSONArray)fieldValue);
	}
	else if (Validator.isNotNull(fieldValue)) {
		jsonObject.put(fieldName, String.valueOf(fieldValue));
	}
}
```
If the fix suggested is merged, then all fields which have a null value will be missing in the JSON Object that represents the DDLRecord. So, the JSON Object won't reflect the real DDLRecord. For instance, if there is a radio field (DDMFormFieldType.RADIO) and its value is null, then the _**else if**_ which treats this field type and the last _**else if**_ will be ignored. Therefore, my suggestion is keep the current code (without the fix) and just add an _**if**_ like this:
```
else {
	if (Validator.isNull(fieldValue)) {
		fieldValue = StringPool.BLANK;
	}

	jsonObject.put(fieldName, String.valueOf(fieldValue));
}
```
In this way, we'll guarantee that every field is added to the JSON Object, even if the field has a null value. Also, the code above has taken the same idea of what is described by you on [LPS-67607](https://issues.liferay.com/browse/LPS-67607) as the real solver. 😉 

Thanks for report the issue and send us a fix. 😄

**Comment by peterborkuti** [comment]
Hi,

Interesting. I think, I was aware of it, and the code some lines above contains this:
```
for (String fieldName : ddmStructure.getFieldNames()) {
		jsonObject.put(fieldName, StringPool.BLANK);
}
```

Is it not enough?

**Comment by natocesarrego** [comment]
Hey @peterborkuti,

You're totally right. This code you've mentioned already does exactly what I've suggested. 😊 I'm sorry to reject your fix. I've tested your fix here and it fixes perfectly the issue.

Do you mind if I create a unit test to cover the scenario of this issue and then forward to Marcellus?

Thanks.

**Comment by peterborkuti** [comment]
Hey @natocesarrego,
No problem. Moreover, It is great, that you invested time to check my fix, it could be bad anytime so please, do it also in the future.

And I would be very happy if you create tests for it and I am sorry for not to do it myself.

Thank you in advance
Péter

**Comment by natocesarrego** [comment]
No problem about the fact you didn't create the test, @peterborkuti. 😉 Our team decided to create tests to every fix to avoid regressions, you know?

One more time, thanks for report this issue and send us a fix.

Thanks.

**Comment by marcellustavares** [comment]
Thanks @peterborkuti @natocesarrego for working on this.

**Pull request closed without merging**
