### PR TITLE
LPS-61889 Relax calendar validation so doesn't fail when exporting

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by juangon** [comment]
Ooops @brandizzi can you close this and make another pull using the last commit I've just made? I missed the first character in the property. Thanks!

**Comment by juangon** [comment]
The new pull is here: https://github.com/brandizzi/liferay-portal/pull/136. Sorry for the inconveniences @brandizzi.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34201. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/a836a32~1...a836a32) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juangon** [comment]
Hi @marcellustavares please can you close this pull? I resent the pull (see previous comment). Thanks!

**Comment by juangon** [comment]
Oh Ok you added it in current pull. Thanks!

**Comment by marcellustavares** [comment]
I went ahead and changed @juangon, it was simpler :) thanks.

**Comment by marcellustavares** [comment]
Could you close brandizzi#136?

**Pull request closed without merging**
