### PR TITLE
LPS-66420 Fix tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@marcellustavares It doesn't seem to be related to what I've done.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40611. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
