### PR TITLE
LPS-51356

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@marcellustavares minor changes.  However, we do have an issue: how to delete completed tasks?  Right now those are not deleted anywhere.  Also, what happens if we have an error in the task?

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
hey @mhan810, all tasks are deleted as soon we delete the structure. Regarding the user feedbacks we need to build a UI so admins could check the background tasks list. AFAIK there's only a way to check staging related tasks currently.

I'll ping the @matethurzo so we can build something like this.

Thanks!

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35211. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
