### PR TITLE
LPS-69018 BuildLang

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/thiago-rocha/liferay-portal/pull/39. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/f36118e~1...f36118e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
