### PR TITLE
[TECHNICAL-SUPPORT] LPS-62885

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ericyanLr

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
hey @ericyanLr @jonathanmccann I don't think this is right, we have the update version login on updateStatus method.

Could you please double check why it isn't be called if that's the case?

Thanks

**Comment by ericyanLr** [comment]
Hey @marcellustavares,

You are correct, the updateStatus method does update the version of the DDL Record.
The DDL Record in the database would actually have the proper version.
But, the issue is mainly with the re-indexing.

Currently when we can call updateRecord, the DDL Record is actually being re-indexed 3 times:
* DDLRecordLocalServiceImpl.**updateRecord**
* DDLRecordLocalServiceImpl.**updateStatus**
* AssetEntryLocalServiceImpl.**updateEntry** (Called within updateStatus)

I'm not sure how the ordering is handled between the 3 re-index calls, but it appears that they are inconsistent. Basically, whichever re-index call that gets called last would be chosen to be the index for the DDL Record.

If it turns out that if the last re-index originates from the DDL Record returned from DDLRecordLocalServiceImpl.**updateRecord**, the indexed record would not contain the latest recordVersion, since the DDL Record object does not contain the latest version.

**As for the proposed changes:**
Since a new recordVersion is added, the DDL Record would be updated with the latest version.
The preceding IF statement with isKeepRecordVersionLabel would determine whether the new recordVersion being added should be kept.

Hopefully that wasn't too confusing, please let me know if you have any other questions!
Thanks!

**Comment by marcellustavares** [comment]
hey @ericyanLr, can you try to remove the indexable annotation on the updateRecord method and see if it fixes your issue?

Thx

**Comment by ericyanLr** [comment]
Hey @marcellustavares,

I have tested removing the indexable annoation on the updateRecord method and it does resolve the issue. Would this be the better approach?

Thanks!

**Pull request closed without merging**
