### PR TITLE
LPS-69162 Regenerate

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
@marcellustavares It'll compile when we add "version" attribute to DDLRecordSet. Thanks!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/320. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/5448c6c~2...5448c6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
