### PR TITLE
LPS-65224 Standardize Whiteboard servlet names

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
hey @vicnate5, did you see this error before? I got the same in different pull requests?

**Comment by vicnate5** [comment]
Yea. This is occuring on lots of pull requests. I am currently looking into it.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39445. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
