### PR TITLE
handle the context in case of error

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@marcellustavares @leoadb 

Did an analysis on the results here

## Issues

#### 1. Cannot add a second instance of a repeatable field
Reproduced with filling out a form with a repeatable text field. Also reproduced when configuring a data provider.

#### 2. JS error and failure to save a form
```
JAVA_SCRIPT_ERROR: TypeError: a is undefined [http://localhost:8080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7003&t=1493401468554&/o/dynamic-data-lists-form-web/admin/js/form_builder_render_rule.js&/o/dynamic-data-lists-form-web/admin/js/form_builder_render_rule_condition.js&/o/dynamic-data-lists-form-web/admin/js/../templates/rule_builder.soy.js&/o/dynamic-data-lists-form-web/admin/js/form_builder_rule_builder.js&/o/dynamic-data-lists-form-web/admin/js/form_builder_util.js&/o/dynamic-data-lists-form-web/admin/js/form_builder.js&/o/dynamic-data-lists-form-web/admin/js/form_definition_serializer.js&/o/dynamic-data-lists-form-web/admin/js/form_layout_serializer.js&/o/dynamic-data-lists-form-web/admin/js/form_portlet.js&/o/dynamic-data-mapping-type-editor/editor_field.js:7]
```
#### 3. Configuration of Calculate, Autofill, and Is Equal To Value rules fail
Not sure if this is a regression or just a test fix. Would need to check manually.

#### 4. Error on upgrade.
```
18:04:07,126 ERROR [main][com_liferay_portal_upgrade:97] Invocation to listener threw exception
    [java] java.lang.RuntimeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.ClassCastException: com.liferay.dynamic.data.mapping.model.DDMFormFieldOptions cannot be cast to com.liferay.dynamic.data.mapping.model.LocalizedValue
```

There are some minor test fixes needed as well.

**Comment by vicnate5** [comment]
Testray link https://testray.liferay.com/home/-/testray/subtasks?testrayTaskId=67392899

**Comment by marcellustavares** [comment]
Thanks @vicnate5, I'll look at those again and retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Pull request closed without merging**
