### PR TITLE
LPS-54033

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @yxingwu

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hi @yxingwu, we'll remove the parent/child structures concept for Liferay 7.0

Is this issue affecting any ee-6.2.x customer?

Thanks

**Comment by yxingwu** [comment]
Hi, @marcellustavares 

Sorry to reply you later. I test it on liferay-portal-ee/ee-6.2.x and I don't find any affecting on ee-6.2.x
This bug should not exist on ee-6.2.x.

Thanks!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/29278.

Thanks @yxingwu, sorry for the delay in pushing this forward.

Regards,

**Pull request closed without merging**
