### PR TITLE
LPS-58352 NullPointerException is thrown when Saving Iframe configuration in Configuration Admin

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-58352](https://issues.liferay.com/browse/LPS-58352).<br><br>/cc @pei-jung @jorgeferrer @hhuijser

### CODE REVIEW

**Comment by drewbrokke** [comment]
This is an edge case where one form field name string ("authName") contains another field name string ("auth") that is also a false checkbox.

**Comment by marcellustavares** [comment]
thanks @drewbrokke, could you add unit tests for this?

**Comment by drewbrokke** [comment]
Sure!  Same branch?

**Comment by marcellustavares** [comment]
It's fine, thanks @drewbrokke!

**Comment by drewbrokke** [comment]
Hey @marcellustavares, I just pushed the unit test.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30632. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/dbf53feb~1...dbf53feb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @drewbrokke :+1:

**Comment by drewbrokke** [comment]
You're welcome!

**Pull request closed without merging**
