### PR TITLE
LPS-66598 Use the right classLoader

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares I am currently writing a test for this. Would be awesome if we could get this in soon.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41259. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/2486d9b~1...2486d9b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
