### PR TITLE
LPS-65091 Fix package name

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @leoadb, @marcellustavares, should we close https://github.com/marcellustavares/liferay-portal/pull/1379 ? It's the same fixed from what I see :)

**Comment by leoadb** [comment]
Hi @jkappler we shouldn't. Same fix but in different classes. @marcellustavares

**Comment by jkappler** [comment]
Hi @leoadb, sorry, saw the exact same. I reopened the PR. Thanks for the heads up

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39134. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@leoadb, I've sent back to you the reversion of LPS-65079 along @jkappler fix because they were related.

I've also reverted partially https://github.com/marcellustavares/liferay-portal/commit/cfaa8dc38763d931ce81ead0b5b94939c14fb034 I'm not sure why we changed the package name on that commit. Could you please double check?

Thanks

**Pull request closed without merging**
