### PR TITLE
LPS-68780 using mvcRenderCommand to set Comment

### PR DESCRIPTION
**Pull request by linolaoj**
New pull following the suggestions from https://github.com/sergiogonzalez/liferay-portal/pull/3540#issuecomment-257240837

Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3549. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
