### PR TITLE
LPS-45479 - disabling validation during checkout

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Tests failures @linolaoj, could you please double check?

**Comment by linolaoj** [comment]
Hi @marcellustavares, the test LayoutImplTest was updated yesterday. I ran the test again today and did not get errors.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2592. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/8fa9fd1~1...8fa9fd1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
