### PR TITLE
LPS-68418 Simplify

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44288. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/0856afd~4...0856afd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/584. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/0856afd~4...0856afd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
