### PR TITLE
LPS-58581 Using auto propagated parameter instead of manually propagation

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
This is fine @rafaprax, thx

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30550. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
