### PR TITLE
Lrac 5823

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
No need to track the deprecated interface as this API is "internal" to AC

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:forward

**Comment by marcellustavares** [comment]
hey @riccardo-ferrari, why do we keeping having major bump after this?

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
Just started reviewing :)

**Comment by marcellustavares** [comment]
forwarded to https://github.com/rachaelkoestartyo/liferay-portal/pull/17

**Pull request closed without merging**
