### PR TITLE
[TECHNICAL-SUPPORT] LPS-82059

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
hey @SamZiemer, could you fwd this pull to @jeyvison? Thanks

**Comment by jeyvison** [comment]
Hey @SamZiemer , actually forward this PR to @rafaprax  please. Thanks :)

**Comment by SamZiemer** [comment]
Sure thing, forwarded here: https://github.com/rafaprax/liferay-portal/pull/708

**Pull request closed without merging**
