### PR TITLE
LPS-59811 Set AlloyEditor as the default editor for ddm text_html field

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @marcellustavares!

This makes AlloyEditor the default editor for ddm text_html fields.

Ideally, I think this should be configurable at the field level, so I've updated the placeholder issue we have pending (https://issues.liferay.com/browse/LPS-59809) to reflect this as well. I'll be so happy If you could take care of this :blush: 

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @vicnate5, @ctampoya, could you take a look and update this failing test? -> `PoshiRunner.test[CPDynamicdatalists#AddListRecordWithHTMLField]`

If I understood correctly from the title, it's trying to add a record to a ddl that contains an html field. I've tried this and it indeed works with the new editor. However, it seems there are some test conditions that apply only to a very specific editor. We should try to be agnostic of the editor, since this could change.

Thanks!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/43. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @jbalsas, I think @brunobasto can handle that.

Regards,

**Pull request closed without merging**
