### PR TITLE
Config Admin bug

### PR DESCRIPTION
**Pull request by brunobasto**
@marcellustavares 

This fixes the JavaScript error, but the repeated values are not being persisted. I'm having a problem with my build right now so I hope you can fix the back-end part of this issue :)

Thx,

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@brunobasto, the index is being wrongly generated in the JS. 

Can we add tests for that, cc @eduardolundgren

Please resend. Thanks

**Comment by brunobasto** [comment]
We have plans for that. In the mean time, I have an alternate solution. I'll show you later.

**Comment by brunobasto** [comment]
@marcellustavares 

Fixed and sent to Nate: https://github.com/marcellustavares/liferay-portal/pull/538

**Pull request closed without merging**
