### PR TITLE
DDM Upgrade Rewview

### PR DESCRIPTION
**Pull request by migue**
The code is perfectly fine from the upgrade perspective. I would like to note that, this change, potentially, could affect to some queries, causing unexpected failures. For example: if you have a select distinct \* (or select distinct name), or, if you have a LIKE clause over the blob, ... I would review all the queries before merging this change, but this is up to Marcellus, this is his domain ;)

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by marcellustavares** [comment]
thx guys!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ChrisKian** [comment]
I've resubmitted the PR here to account for DDMTemplate: https://github.com/marcellustavares/liferay-portal/pull/1665

I've also provided an explanation for my changes.  Feel free to close this PR.  Thanks!

**Pull request closed without merging**
