### PR TITLE
LPS-63459 Removed because expressions are built using functions not supported

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares Hope it's ok now.

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36599. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/1e5348f~6...1e5348f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
