### PR TITLE
LPS-51921 Adding tests

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by marcellustavares** [comment]
wowwwww tests :+1: what about js tests? :smile:

**Comment by marcellustavares** [comment]
cc @henvic

**Comment by brunobasto** [comment]
Actually, those tests are just basic tests. I still need to write cases for
nested fields and etc, just like henrique did. I removed his tests because
of changes I did. But I'll reference his tests cases when writing the new
ones.

wowwwww tests [image: :+1:] what about js tests? [image: :smile:]

—
Reply to this email directly or view it on GitHub
<https://github.com/marcellustavares/liferay-portal/pull/410#issuecomment-71930657>
.

**Comment by marcellustavares** [comment]
Pull request forwarded to https://github.com/brunobasto/liferay-portal/pull/219. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
