### PR TITLE
[TECHNICAL-SUPPORT] LPS-71794

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by SpencerWoo** [comment]
Hi @marcellustavares, any updates on this?

**Comment by marcellustavares** [comment]
Sorry for the delay. Will push this today.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48693. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
