### PR TITLE
LPS-68661 apply to template

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/577. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/318b495~1...318b495) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
