### PR TITLE
LPS-60722 Extract aui:translation-manager taglib to ddm:translation-manager

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
hey @jbalsas, @mjbradford89 isn't translation manager generated? I couldn't see any entry in liferay-ddm.xml. See https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/liferay-aui.xml#L1593

Could you please resend?

Thanks

**Comment by mjbradford89** [comment]
hey @marcellustavares, yes you're right.  I'll make the corresponding changes to liferay-ddm.xml and resend.  Thanks!

**Comment by marcellustavares** [comment]
Thanks @mjbradford89, please remove the definition from the aui.xml file and also run buildTaglib on ddm taglib module to make sure we're not missing anything :)

Thanks a lot for the help!

**Comment by mjbradford89** [comment]
New pull submitted here: https://github.com/marcellustavares/liferay-portal/pull/1079

Thanks! :)

**Comment by jbalsas** [comment]
Sorry, @marcellustavares, I didn't realize you were autogenerating the ddm taglibs :disappointed: 

@mjbradford89 thanks a lot for resending! :blush:

**Pull request closed without merging**
