### PR TITLE
LPS-72846 Check if workflow is in progress

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49335. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
