### PR TITLE
WIP2

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares Needs some source format but it seems to work !!! :)

**Comment by marcellustavares** [comment]
Awesome @leoadb, thanks

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Merged locally. Thanks

**Pull request closed without merging**
