### PR TITLE
LPS-69019 fix unit test

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by diogo-lins** [comment]
ci:open

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1748. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
