### PR TITLE
LPS-60361 Remove duplicate class UpgradePortletPreferences

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/628. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
