### PR TITLE
LPS-62789

### PR DESCRIPTION
**Pull request by vicnate5**
See https://github.com/brianchandotcom/liferay-portal/pull/35334 and https://github.com/brianchandotcom/liferay-portal/pull/35312. I think a bug was fixed and it revealed an issue in workflow. This fixes the behavior to match how it has been in master and 6.2 in the past.

Most importantly, this also fixes our tests on the PR tester.

### CODE REVIEW

**Comment by marcellustavares** [comment]
Awesome, thx @vicnate5

**Comment by vicnate5** [comment]
Ok. this didn't fix all the issues. Gonna push in workaround on our tests until we can decide what to do about this.

**Comment by vicnate5** [comment]
Sent test workaround https://github.com/brianchandotcom/liferay-portal/pull/35343

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
