### PR TITLE
LPS-69123 SF - Pass objects to take advantage of the type system.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
(This is weird, I could not find anything compatible with the message

> java.lang.Exception: There should be an empty line before line '75', as we finished referencing variable 'group': ../../../modules/apps/forms-and-workflow/calendar/calendar-test/src/testIntegration/java/com/liferay/calendar/service/test/CalendarResourceServiceTest.java 75

[the logs](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4,label_exp=!master/54608/testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/) show...)

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45296. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
