### PR TITLE
master-vw-43

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-19036 
@jbalsas, this should fix failing poshi due to your changes. The way that poshi inputs into ckeditors makes it difficult for us to be editor agnostic.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @vicnate5, all input editors expose a common JS API `window['<%= name %>'].setData`. Couldn't we use that instead?

I assume the goal of the test is to assert the correct behaviour of ddm, and not that pressing some keys produces some effect, which in this case, we should assert for every possible available editor...

**Comment by vicnate5** [comment]
@jbalsas Thanks for the response. You are correct the test does not need to assert the key presses in this case. Poshi currently uses `.setHTML` for the default CKEditor and `.setData` for AlloyEditor. I am not entirely sure why we originally chose to use different methods, but with portal moving to Alloy Editor, our tests should soon all be running on the better, more agnostic, method.

**Comment by jbalsas** [comment]
Hey @vicnate5, fair enough. Hopefully we can get more robust tests as time goes by.

Thanks for fixing this one! :+1:

**Comment by marcellustavares** [comment]
thanks guys!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31704. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
