### PR TITLE
master-vw-133

### PR DESCRIPTION
**Pull request by vicnate5**
@pedroqueiroz94 @inacionery The reason this pull was failing on the CI but not locally is because the CI test moves faster than on your machine. It was finding the FILTER locator on the previous screen during the page load. I fixed it by having the test assert an element unique to the specific page before clicking on the filter.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34167. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/7fe5522~4...7fe5522) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
