### PR TITLE
LPS-69019 Serializing the value of select to send in array format

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1785. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/4d56d11~1...4d56d11) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
