### PR TITLE
Revert "LPS-59306 - make child field key avilable for template"

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
Hi @marcellustavares, 
i revert this issue because the nested fields shouldn't appear in palette. If they show up they may confuse the user.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31597. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@inacionery, what's the ticket number that this revert solves?

**Comment by inacionery** [comment]
@marcellustavares Done.

**Pull request closed without merging**
