### PR TITLE
LPS-60131 Regenerate

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31798. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/bd2ea3e~1...bd2ea3e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
