### PR TITLE
Lps 58633

### PR DESCRIPTION
**Pull request by ligasm**
Hi @marcellustavares

@eduardolundgren directed me to you. Could you have a look at this if I'm going the right way. It's still work in progress but I would like to have it validated first.

Let me know what you think. 
@sammso you might be interested in this.

### CODE REVIEW

**Comment by sammso** [comment]
@ligasm, yes this is good stuff, I think your commit structure is easy to read which describes nicely the solution.

I don't have time to test this, but good stuff.

**Comment by ligasm** [comment]
I added a small fix. Liferay was not starting but now it seems that it's working.

**Comment by ligasm** [comment]
adding @brunobasto

**Comment by marcellustavares** [comment]
Thanks @ligasm! I'll try to push this fwd today.

**Comment by ligasm** [comment]
OK now it's fully working and it's tested :)

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/75. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/d1bc0d2~1...d1bc0d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
