### PR TITLE
LPS-60609 Modify source-formatter.properties

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by marcellustavares** [comment]
hey @leoadb, are we displaying the exception messages in the UI?

**Comment by leoadb** [comment]
@marcellustavares no validation message is displayed today, user has no feedback about what happened. I guess frontend and backend should both deal with this. What do you think ?

**Comment by marcellustavares** [comment]
Definitely, I was just wondering b/c I saw these changes on the language.properties and I was not sure if they were being used.

Thanks

**Comment by leoadb** [comment]
@marcellustavares I've modified the page edit_record_set.jsp to include liferay-ui:error entry for each custom exception I've created.

**Comment by leoadb** [comment]
@marcellustavares I also modified test classes to catch the new exceptions

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/134. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/d94410b~5...d94410b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
