### PR TITLE
LPS-58020 - Change local variable type to fix compilation error in test "DDMFormValuesValidatorTest".

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Beautiful, I've already miss you! :cry:

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/777. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/bf006b0~1...bf006b0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
love you @natocesarrego  :heart:

**Comment by natocesarrego** [comment]
Nice! Finally all the tests passed! :) Soon I'll be back, baron.

**Pull request closed without merging**
