### PR TITLE
LPS-72843 Unescape the values to be included in the notification email

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi Roberto,

This is a followup of this pull request: https://github.com/robertoDiaz/liferay-portal/pull/581
Per your request I fixed the problematic test.

Could you please review my changes?

Thank you,
Laci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/367. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @robertoDiaz 👍

**Pull request closed without merging**
