### PR TITLE
LPS-59330 Propagate parameters in deleteUrl to avoid wrong redirect when an exception is thrown in the deleteTemplate operation

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@rafaprax, shouldn't we do the same for deleteStructure operation?

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32517. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/bf75755~1...bf75755) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
