### PR TITLE
[TECHNICAL-SUPPORT] LPS-68432

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @jonathanmccann

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43821. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
