### PR TITLE
[TECHNICAL-SUPPORT] LPS-71943, LPS-72136

### PR DESCRIPTION
**Pull request by Alec-Shay**
Re-sent from https://github.com/marcellustavares/liferay-portal/pull/1858 with https://github.com/Alec-Shay/liferay-portal/commit/47b6a95736d26237c98e2bbee9a29a14c4441a96 added.

Please see the comments on https://github.com/marcellustavares/liferay-portal/pull/1858 as well as [LPS-72136](https://issues.liferay.com/browse/LPS-72136) for details on the added commit. Also please note that [LPS-72141](https://issues.liferay.com/browse/LPS-72141) was discovered as a bug in master while testing, as well.

Thank you.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Hello @marcellustavares,

Thank you for looking at the previous pull request. Can you take a look at this one soon too?

Thanks!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @Alec-Shay!

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48694. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
Thanks!

**Pull request closed without merging**
