### PR TITLE
[TECHNICAL-SUPPORT ] LPS-55342 Validate if the user who created the workflow instance still exist

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-55342

/cc @hudakl

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hi @lipusz, could you please resend this after https://github.com/brianchandotcom/liferay-portal/pull/26248 gets merged?

We're extracting the workflow modules out.

Thanks a lot!

**Comment by lipusz** [comment]
@Laci: please adapt our changes once https://github.com/brianchandotcom/liferay-portal/pull/26248 gets merged & resend to me.

@Marcellus: apart from the modularization, is our approach is suitable for you? If so, Laci can start backporting it to the customer's version, so we can also proceed in the meantime by releasing an SDH.

Thank you in advance,
Tibor

@marcellustavares @hudakl

**Comment by marcellustavares** [comment]
sounds good @lipusz, thanks!

**Comment by lipusz** [comment]
Hi Marcellus,

I'm not completely sure about your response. :-) Did you mean "sounds good" that the solution is fine?
Sorry for my stupidity. :dancer: 

Br,
Tibi
@marcellustavares

**Comment by marcellustavares** [comment]
I thought I should have said "looks good" :smile: , anyway the solutions is fine!

I was just wondering if we could potentially have the same problem in the workflow tasks portlet, I guess not right?

Thanks

**Comment by lipusz** [comment]
Well, I didn't test the Workflow Tasks protlet when I was reviewing Laci's
changes, so it should be checked. @Laci: can you please do it, too?

Thx!

@hudakl, @marcellustavares

On Thu, May 7, 2015 at 11:40 AM, Marcellus Tavares <notifications@github.com
> wrote:

> I thought I should have said "looks good" [image: :smile:] , anyway the
> solutions is fine!
>
> I was just wondering if we could potentially have the same problem in the
> workflow tasks portlet, I guess not right?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcellustavares/liferay-portal/pull/477#issuecomment-99795268>
> .
>



-- 

*Tibor LIPUSZ*

Senior Engineer, TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by hudakl** [comment]
Hi,

I'll check the Workflow Tasks as well and adapt the fix according to brianchandotcom#26248

Thanks,
Laci

**Comment by lipusz** [comment]
Hi Laci,

LPS-54927 has been merged to master. Please, adjust your changes to the modularized logic and resend.

Thanks!

@hudakl

**Pull request closed without merging**
