### PR TITLE
LRAC-6171 Add IE11 polyfills

### PR DESCRIPTION
**Pull request by fcodias**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started reviewing :)

**Comment by fcodias** [comment]
ci:test:sf

**Comment by fcodias** [comment]
ci:forward

**Comment by fcodias** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Comment by fcodias** [comment]
ci:forward

**Comment by marcellustavares** [comment]
Just started reviewing :)

**Comment by marcellustavares** [comment]
resent to https://github.com/marcellustavares/liferay-portal/pull/1963

**Pull request closed without merging**
