### PR TITLE
Fix DDM Upgrade Problem

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @migue

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@cgoncas, could you please paste a stack trace for the error? We have a bunch of tests yet to be merged at https://github.com/marcellustavares/liferay-portal/pull/1129 and we can add a proper tests for this case.

Also the tests are failing :(

Thanks a lot!

**Pull request closed without merging**
