### PR TITLE
LPS-70112 BuildService

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/119. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/5d1ebf5~1...5d1ebf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
