### PR TITLE
LPS-68654 - New Polls UI Issues (alignment/order, Lexicon design)

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-68654

### CODE REVIEW

**Comment by dustinryerson** [comment]
Would it be better for these commits to go under https://issues.liferay.com/browse/LPS-67026?

**Comment by marcellustavares** [comment]
hey @dustinryerson, thanks for the fix. Do you want me to change the LPS number in the commits?

**Comment by dustinryerson** [comment]
Hey @marcellustavares, I think changing LPS number in the commits to use LPS-67026 rather than LPS-68654 might be best because LPS-67026 seems to better represent the changes being made overall. Originally I was just fixing LPS-68654 but more improvements were made during the review process that cover more issues than just the position of the delete button.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks for the update @pat270 @jonmak08 @dustinryerson!

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43998. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/a6a13e4~1...a6a13e4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
