### PR TITLE
LPS-54300 Update taglibs

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Marcellus,

This looks way better than before. Having entities like DDMForm will make things much easier to use and handle. 

I'm ccing the Collab team so they are aware of the changes too.

Thanks for doing this!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @izaera @adolfopa

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks for reviewing this @sergiogonzalez!

**Comment by sergiogonzalez** [comment]
Yup! Thank you and sorry again for the delay :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25100. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
