### PR TITLE
LPS-58073

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Thanks @jorgediaz-lr, could you please create one test case for this bug?

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @marcellustavares,

I have created a new test and resend the pull request with a new commit

**Comment by marcellustavares** [comment]
Wonderful! Thanks a lot @jorgediaz-lr

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29543. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/445f7c8~2...445f7c8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
