### PR TITLE
biuldSoy

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
All Forms tests failed. Forms admin portlet is missing from Liferay > Content.

**Comment by brunobasto** [comment]
Hey @vicnate5, yeah, I know. This one is a work in progress. I'm asking Marcellus to help me investigate it. We are not gonna merge it this way :)

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1284. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/088ce7c~4...088ce7c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
