### PR TITLE
LPS-55933 renamed

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26968. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@leoadb, unfortunately I had to reset your commit b/c the generated languages were in the same commit.

Please add the microsoft* key to your build.properties in order to proper generate the lang keys.

Thanks

**Comment by leoadb** [comment]
@marcellustavares I modified my settings properly. Next one will be correct. Sorry :)

**Pull request closed without merging**
