### PR TITLE
LRAC-11078

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-11078

Please see the changes in asah in https://github.com/liferay/com-liferay-osb-asah-private/pull/3626

/cc @riccardo-ferrari

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
