### PR TITLE
[TECH SUPPORT] LPS-66257

### PR DESCRIPTION
**Pull request by giros**
Hi Marcellus,

Please review. See https://issues.liferay.com/browse/LPS-66257 for details.

Regards,
G

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hi @zsolah, thanks for the fix, I'm just wondering about template permissions, wouldn't it have the same issue?

Thanks

**Comment by marcellustavares** [comment]
cc @giros

**Comment by zsolah** [comment]
Hi @marcellustavares ,

I was focusing the use case with asset publisher, I'm not sure how this affects DDMTemplate.
On the administration screen of structures and templates the inlineSQLPermission check was used, and this way the structures/templates with view permission have appeared.

Regards.

**Comment by marcellustavares** [comment]
@zsolah, is there a way to create a test case for this?

**Comment by zsolah** [comment]
@marcellustavares 
I've done a quick search for the usages of "DDMTemplatePermission.contains(" , and I haven't found the same bug where a template's groupId was passed as parameter.

**Comment by marcellustavares** [comment]
hey @zsolah, any updates regarding the tests :) thx

**Comment by zsolah** [comment]
Hi,
I will make the test tomorrow.

**Comment by zsolah** [comment]
I'm sorry I didn't have time for it.

**Comment by zsolah** [comment]
It has turned out, the real issue was to be able to assign such Site Role permissions for global entries. See https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/21815538 .
New LPS: https://issues.liferay.com/browse/LPS-66684
So this should be closed.

**Comment by marcellustavares** [comment]
Cool, thx @zsolah!

**Pull request closed without merging**
