### PR TITLE
LPS-59397 Since all searches will be lowercase, so should they be on tests

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
cc @arboliveira: I did like we talked, but the "like" feature did not work. Since this is not the current bug, I'm proceeding with the current fix anyway.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @brandizzi and @inacionery!

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31832. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
