### PR TITLE
CEREBRO-1337 Add fileEntryId in a Document Library analytics events

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test

**Comment by interaminense** [comment]
ci:reopen

**Comment by interaminense** [comment]
ci:test

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/andreldm/liferay-portal/pull/3. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/68298734f009~3...68298734f009) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
