### PR TITLE
LPS-62881 Fix test

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@jcampoy, @inacionery simplified the index attribute on journal article images. Is this going to affect your other fix?

Thanks

**Comment by jcampoy** [comment]
Hey @marcellustavares , I think this change doesn't affect the other fix.
Thank you both.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/4014. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/467e8de~1...467e8de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @jcampoy.

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/16. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/467e8de~1...467e8de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
