### PR TITLE
LPS-67593 checking if workflowTask is still accessible

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43898. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/2ea11bb~1...2ea11bb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
