### PR TITLE
pull-request-23147

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @marcellustavares 

I wanted you to review / rewrite this pull because it deals a bit with DDM, and, because you do such a good job at making the naming consistent so that everything is obvious. I'm not able to tell from the var names what does what, so I'd like you to rewrite this for me. You have more time than me, so I have to delegate this to you. Thanks for helping bro.

**Comment by marcellustavares** [comment]
No problem @brianchandotcom, will add to my queue.

Regards

**Comment by rotty3000** [comment]
I don't understand why this requires a rewrite!

@brianchandotcom can you explain what's not obvious?

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/706. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
