### PR TITLE
LPS-56908 Add some unit tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@rafaprax, could you please add some tests to DDMFormValues as well? We'll use @leoadb utility to deep copy this entity as well.

Let's just push this first and could you hold the StorageManager pull until this gets to the upstream?

Thanks

**Comment by marcellustavares** [comment]
I think this is a random one @leoadb

**Comment by leoadb** [comment]
yeah @marcellustavares :)

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Ok @marcellustavares :)

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28088. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
