### PR TITLE
LPS-62181 Fix notNull validation. Use freemarker operator to check if object or attribute is not null

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@rafaprax is back :)

**Comment by rafaprax** [comment]
:)

**Comment by marcellustavares** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34737. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
