### PR TITLE
[TECHNICAL-SUPPORT] LPS-71943

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Alec-Shay

### CODE REVIEW

**Comment by marcellustavares** [comment]
@jonathanmccann, I'm a little bit concerned with the impact this may cause on the export/import. I'm not sure if we took that into consideration.

@Alec-Shay, could you please verify that we're not causing regression while exporting/importing lar files?

Thanks a lot!

**Comment by Alec-Shay** [comment]
Hello @marcellustavares,

To confirm what you mean, do you mean a LAR file of the DDL Display portlet's configuration? If so, what kind of issues might I be looking for? All I can think of would be a case where it's imported to a site that doesn't have the same parent site(s), but then it would just seem to revert to the default templates.

Is there another case we should be concerned with that I'm not considering?

**Comment by Alec-Shay** [comment]
@marcellustavares I just tested the case I previously mentioned to be sure, and actually, it doesn't handle it as gracefully as I thought, and can throw an NPE in this case.

Still, just to be on the safe side --was that what you had in mind, or is there anything else to consider, too? Thanks!

**Comment by marcellustavares** [comment]
hey @Alec-Shay, yeah that was my concern, specially during the export that we should reference the global strong reference and during import in the way we handle those dependencies.

So basically two main scenarios:

1. Export/Import with no global references in the configuration
2. Export/Import with the global reference in the configuration

The import phase could have four variations: same or different site, with existing or no existing data.

This would probably handle the basic use case.

Thanks for looking into this!

**Comment by Alec-Shay** [comment]
@marcellustavares Thank you for describing that in detail. I'm looking into it now, and there will likely need to be at least a couple of other changes; for starters, I found that there seems to be another bug in master where the `DDLDisplayTemplateHandler` class isn't being picked up by the `TemplateHandlerRegistry`, causing issues with the portlet reading display templates in general (seems to be a separate bug, but probably should be fixed together). Additionally, I haven't even tested out all the cases you've mentioned yet, but it does seem like the export includes missing references it shouldn't need to, even without these changes.

I'll probably have to find out what the correct behavior should be for some of these cases, and end up resending this pull.

**Comment by Alec-Shay** [comment]
@marcellustavares So, after looking into this quite a bit, as I was afraid of, this appears to be a much more complex issue than I originally thought.

Thankfully, the `DDLDisplayTemplateHandler` issue seems to be simple, and I have a way to fix it (although, I think at some point we should probably consider the consequences of [LPS-70310](https://issues.liferay.com/browse/LPS-70310), because it really opens up vulnerability to these kinds of issues). That bug is only in master (I may want to open up a separate ticket for it, but submit it together).

The main problems I'm seeing with export/import for parent/Global sites, though, is that it overall doesn't seem to work too well for the dependencies. Even ignoring the DDL Display portlet, if I have a list based on a Global or parent structure that has Global or parent templates, it seems really cumbersome and difficult to find a way to import it successfully to a different instance. I haven't gone all the way into the details of this yet, but I have a feeling it may be complicated and could take a while to work out how it should really be working -- which is unfortunate, because it gets in the way of exporting/importing the DDL Display portlet configuration, too.

This fix doesn't actually affect what is exported or imported at all for the portlet's configuration though. Global structures can already be selected in the configuration, and this fix just allows Global templates to be selected, too -- which either way, would have to be exported/imported as references if the Global structure were used. The content of the LAR (and how it's exported/imported) is totally unchanged by this. So while these bugs seem pretty bad for the DDL Display portlet, they are existing bugs, and not regressions of these changes.

I do think these bugs definitely shouldn't be ignored, but I'm concerned it would drastically delay getting a fix for a customer if we needed to fix all those issues together with this. Do you think we would need to fix these other existing bugs to introduce this change too, or can we investigate that separately? Or, in other words, can we limit the scope of what would need to be fixed to push this through for a customer?

I can gladly re-send this together with a fix for the other `DDLDisplayTemplateHandler` bug in master, because finding the cause essentially gave me the solution with it -- but I'd like to get your opinion on the other issue(s).

Thank you.

**Comment by marcellustavares** [comment]
Thanks @Alec-Shay for the detailed explanation. I think we could handle the remaining bugs in separate tickets if they are not directly related to this pull. I'm totally fine with this.

Could you please file the tickets you found in Jira tho? So we can have this information registered somewhere.

We're planing a official release by June and we'll try our best to address them.

Let me know if I can push this pull fwd or if you want to include any additional commit.

Thanks a lot!

**Comment by Alec-Shay** [comment]
Yeah, definitely. I'll create a couple of LPS tickets in just a moment. I want to include at least one more commit for the `DDLDisplayTemplateHandler` issue (and I'll create a new ticket for that as well), because although it doesn't affect ee-7.0.x, the effects are pretty bad. I can re-send this with that commit for clarity's sake.

Thanks, @marcellustavares!

**Comment by marcellustavares** [comment]
Just push one more commit to this branch @Alec-Shay. Thanks

**Comment by Alec-Shay** [comment]
@marcellustavares Sorry, I can't just push it here because I don't own the branch. I'm creating the LPS tickets now (just created [LPS-72136](https://issues.liferay.com/browse/LPS-72136)).

**Comment by Alec-Shay** [comment]
Forgot to link the re-send: https://github.com/marcellustavares/liferay-portal/pull/1863

**Pull request closed without merging**
