### PR TITLE
LPS-63583 When SPA is enabled, load everything files because the performance gain is already there.

### PR DESCRIPTION
**Pull request by brunobasto**
@marcellustavares, I'm not sure what do I have to do to compile kernel now.

/cc @eduardolundgren
This is a follow up on our conversation.

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brunobasto** [comment]
@marcellustavares I think those failures are unrelated. We may have to publish a new version of the kernel or portal impl for those changes to apply, though

**Comment by marcellustavares** [comment]
yeah, Brian will publish a new version as soon this gets merged. I'll just fwd this to him.

Thx

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37168. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
