### PR TITLE
LPS-69333 check if group exists

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/746. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
