### PR TITLE
LPS-57110 Check for null

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Nice thx a lot @csierra!

**Comment by csierra** [comment]
hey @marcellustavares,

is this still relevant?

Bests!

**Comment by marcellustavares** [comment]
still is @csierra, we'll be pushing this during this week. it got on hold due ddm migration.

thx

**Comment by csierra** [comment]
I was removing branches and I just did not know whether I could delete this one or not. I will keep it alive a bit more then :smile:

**Comment by marcellustavares** [comment]
@pablocp, have you rebased with this pull request already? Can I close it?

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@csierra, I've merged this locally. You may delete your remote :)

Thanks

**Pull request closed without merging**
