### PR TITLE
LPS-69590 Apply serializer

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares Please do a quick look on that. Thanks !!!

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46255. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/9b651d1~2...9b651d1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
