### PR TITLE
LPS-56224 - SF.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27459. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @natocesarrego, this was a beautiful pull request :heart_eyes:

**Comment by natocesarrego** [comment]
Thanks you too, @marcellustavares !

**Pull request closed without merging**
