### PR TITLE
LPS-63898 Add UpgradeJournalTest

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks a lot @inacionery, I've skipped the portal-cache commit b/c I was getting rebase issues.

There was recent modifications in the module build and maybe the cyclic dependency you fixed is already solved? Please send a separate pull if we still need it.

Regards,

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37876. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/784b82c~1...784b82c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
