### PR TITLE
LPS-68782 Validate required fields after rule evaluation

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares Please, send to @brunobasto after your review. Thanks !!!

**Comment by leoadb** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
@leoadb, could you add unit tests?

**Comment by leoadb** [comment]
@marcellustavares Sure. I forgot, sorry. :)

**Pull request closed without merging**
