### PR TITLE
LPS-57100 Regenerate

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28405. [See changes here.](https://github.com/marcellustavares/liferay-portal/compare/ee9da2d~3...ee9da2d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
